//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.Common.BSFrameworkService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.beltransoft.com/", ConfigurationName="BSFrameworkService.PageServiceSoap")]
    public interface PageServiceSoap {
        
        // CODEGEN: Generating message contract since element name appName from namespace http://www.beltransoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.beltransoft.com/GetPageConfig", ReplyAction="*")]
        BS.Common.BSFrameworkService.GetPageConfigResponse GetPageConfig(BS.Common.BSFrameworkService.GetPageConfigRequest request);
        
        // CODEGEN: Generating message contract since element name appName from namespace http://www.beltransoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.beltransoft.com/SavePage", ReplyAction="*")]
        BS.Common.BSFrameworkService.SavePageResponse SavePage(BS.Common.BSFrameworkService.SavePageRequest request);
        
        // CODEGEN: Generating message contract since element name page from namespace http://www.beltransoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.beltransoft.com/DeletePage", ReplyAction="*")]
        BS.Common.BSFrameworkService.DeletePageResponse DeletePage(BS.Common.BSFrameworkService.DeletePageRequest request);
        
        // CODEGEN: Generating message contract since element name appName from namespace http://www.beltransoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.beltransoft.com/GetPageList", ReplyAction="*")]
        BS.Common.BSFrameworkService.GetPageListResponse GetPageList(BS.Common.BSFrameworkService.GetPageListRequest request);
        
        // CODEGEN: Generating message contract since element name fieldName from namespace http://www.beltransoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.beltransoft.com/GetPageListItems", ReplyAction="*")]
        BS.Common.BSFrameworkService.GetPageListItemsResponse GetPageListItems(BS.Common.BSFrameworkService.GetPageListItemsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPageConfigRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPageConfig", Namespace="http://www.beltransoft.com/", Order=0)]
        public BS.Common.BSFrameworkService.GetPageConfigRequestBody Body;
        
        public GetPageConfigRequest() {
        }
        
        public GetPageConfigRequest(BS.Common.BSFrameworkService.GetPageConfigRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.beltransoft.com/")]
    public partial class GetPageConfigRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pageId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pageName;
        
        public GetPageConfigRequestBody() {
        }
        
        public GetPageConfigRequestBody(string appName, string pageId, string pageName) {
            this.appName = appName;
            this.pageId = pageId;
            this.pageName = pageName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPageConfigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPageConfigResponse", Namespace="http://www.beltransoft.com/", Order=0)]
        public BS.Common.BSFrameworkService.GetPageConfigResponseBody Body;
        
        public GetPageConfigResponse() {
        }
        
        public GetPageConfigResponse(BS.Common.BSFrameworkService.GetPageConfigResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.beltransoft.com/")]
    public partial class GetPageConfigResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPageConfigResult;
        
        public GetPageConfigResponseBody() {
        }
        
        public GetPageConfigResponseBody(string GetPageConfigResult) {
            this.GetPageConfigResult = GetPageConfigResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePage", Namespace="http://www.beltransoft.com/", Order=0)]
        public BS.Common.BSFrameworkService.SavePageRequestBody Body;
        
        public SavePageRequest() {
        }
        
        public SavePageRequest(BS.Common.BSFrameworkService.SavePageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.beltransoft.com/")]
    public partial class SavePageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string page;
        
        public SavePageRequestBody() {
        }
        
        public SavePageRequestBody(string appName, string page) {
            this.appName = appName;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePageResponse", Namespace="http://www.beltransoft.com/", Order=0)]
        public BS.Common.BSFrameworkService.SavePageResponseBody Body;
        
        public SavePageResponse() {
        }
        
        public SavePageResponse(BS.Common.BSFrameworkService.SavePageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SavePageResponseBody {
        
        public SavePageResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePage", Namespace="http://www.beltransoft.com/", Order=0)]
        public BS.Common.BSFrameworkService.DeletePageRequestBody Body;
        
        public DeletePageRequest() {
        }
        
        public DeletePageRequest(BS.Common.BSFrameworkService.DeletePageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.beltransoft.com/")]
    public partial class DeletePageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string page;
        
        public DeletePageRequestBody() {
        }
        
        public DeletePageRequestBody(string page) {
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePageResponse", Namespace="http://www.beltransoft.com/", Order=0)]
        public BS.Common.BSFrameworkService.DeletePageResponseBody Body;
        
        public DeletePageResponse() {
        }
        
        public DeletePageResponse(BS.Common.BSFrameworkService.DeletePageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeletePageResponseBody {
        
        public DeletePageResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPageListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPageList", Namespace="http://www.beltransoft.com/", Order=0)]
        public BS.Common.BSFrameworkService.GetPageListRequestBody Body;
        
        public GetPageListRequest() {
        }
        
        public GetPageListRequest(BS.Common.BSFrameworkService.GetPageListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.beltransoft.com/")]
    public partial class GetPageListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        public GetPageListRequestBody() {
        }
        
        public GetPageListRequestBody(string appName) {
            this.appName = appName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPageListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPageListResponse", Namespace="http://www.beltransoft.com/", Order=0)]
        public BS.Common.BSFrameworkService.GetPageListResponseBody Body;
        
        public GetPageListResponse() {
        }
        
        public GetPageListResponse(BS.Common.BSFrameworkService.GetPageListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.beltransoft.com/")]
    public partial class GetPageListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPageListResult;
        
        public GetPageListResponseBody() {
        }
        
        public GetPageListResponseBody(string GetPageListResult) {
            this.GetPageListResult = GetPageListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPageListItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPageListItems", Namespace="http://www.beltransoft.com/", Order=0)]
        public BS.Common.BSFrameworkService.GetPageListItemsRequestBody Body;
        
        public GetPageListItemsRequest() {
        }
        
        public GetPageListItemsRequest(BS.Common.BSFrameworkService.GetPageListItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.beltransoft.com/")]
    public partial class GetPageListItemsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fieldName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string orderBy;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string orderType;
        
        public GetPageListItemsRequestBody() {
        }
        
        public GetPageListItemsRequestBody(string fieldName, string orderBy, string orderType) {
            this.fieldName = fieldName;
            this.orderBy = orderBy;
            this.orderType = orderType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPageListItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPageListItemsResponse", Namespace="http://www.beltransoft.com/", Order=0)]
        public BS.Common.BSFrameworkService.GetPageListItemsResponseBody Body;
        
        public GetPageListItemsResponse() {
        }
        
        public GetPageListItemsResponse(BS.Common.BSFrameworkService.GetPageListItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.beltransoft.com/")]
    public partial class GetPageListItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPageListItemsResult;
        
        public GetPageListItemsResponseBody() {
        }
        
        public GetPageListItemsResponseBody(string GetPageListItemsResult) {
            this.GetPageListItemsResult = GetPageListItemsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PageServiceSoapChannel : BS.Common.BSFrameworkService.PageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PageServiceSoapClient : System.ServiceModel.ClientBase<BS.Common.BSFrameworkService.PageServiceSoap>, BS.Common.BSFrameworkService.PageServiceSoap {
        
        public PageServiceSoapClient() {
        }
        
        public PageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BS.Common.BSFrameworkService.GetPageConfigResponse BS.Common.BSFrameworkService.PageServiceSoap.GetPageConfig(BS.Common.BSFrameworkService.GetPageConfigRequest request) {
            return base.Channel.GetPageConfig(request);
        }
        
        public string GetPageConfig(string appName, string pageId, string pageName) {
            BS.Common.BSFrameworkService.GetPageConfigRequest inValue = new BS.Common.BSFrameworkService.GetPageConfigRequest();
            inValue.Body = new BS.Common.BSFrameworkService.GetPageConfigRequestBody();
            inValue.Body.appName = appName;
            inValue.Body.pageId = pageId;
            inValue.Body.pageName = pageName;
            BS.Common.BSFrameworkService.GetPageConfigResponse retVal = ((BS.Common.BSFrameworkService.PageServiceSoap)(this)).GetPageConfig(inValue);
            return retVal.Body.GetPageConfigResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BS.Common.BSFrameworkService.SavePageResponse BS.Common.BSFrameworkService.PageServiceSoap.SavePage(BS.Common.BSFrameworkService.SavePageRequest request) {
            return base.Channel.SavePage(request);
        }
        
        public void SavePage(string appName, string page) {
            BS.Common.BSFrameworkService.SavePageRequest inValue = new BS.Common.BSFrameworkService.SavePageRequest();
            inValue.Body = new BS.Common.BSFrameworkService.SavePageRequestBody();
            inValue.Body.appName = appName;
            inValue.Body.page = page;
            BS.Common.BSFrameworkService.SavePageResponse retVal = ((BS.Common.BSFrameworkService.PageServiceSoap)(this)).SavePage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BS.Common.BSFrameworkService.DeletePageResponse BS.Common.BSFrameworkService.PageServiceSoap.DeletePage(BS.Common.BSFrameworkService.DeletePageRequest request) {
            return base.Channel.DeletePage(request);
        }
        
        public void DeletePage(string page) {
            BS.Common.BSFrameworkService.DeletePageRequest inValue = new BS.Common.BSFrameworkService.DeletePageRequest();
            inValue.Body = new BS.Common.BSFrameworkService.DeletePageRequestBody();
            inValue.Body.page = page;
            BS.Common.BSFrameworkService.DeletePageResponse retVal = ((BS.Common.BSFrameworkService.PageServiceSoap)(this)).DeletePage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BS.Common.BSFrameworkService.GetPageListResponse BS.Common.BSFrameworkService.PageServiceSoap.GetPageList(BS.Common.BSFrameworkService.GetPageListRequest request) {
            return base.Channel.GetPageList(request);
        }
        
        public string GetPageList(string appName) {
            BS.Common.BSFrameworkService.GetPageListRequest inValue = new BS.Common.BSFrameworkService.GetPageListRequest();
            inValue.Body = new BS.Common.BSFrameworkService.GetPageListRequestBody();
            inValue.Body.appName = appName;
            BS.Common.BSFrameworkService.GetPageListResponse retVal = ((BS.Common.BSFrameworkService.PageServiceSoap)(this)).GetPageList(inValue);
            return retVal.Body.GetPageListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BS.Common.BSFrameworkService.GetPageListItemsResponse BS.Common.BSFrameworkService.PageServiceSoap.GetPageListItems(BS.Common.BSFrameworkService.GetPageListItemsRequest request) {
            return base.Channel.GetPageListItems(request);
        }
        
        public string GetPageListItems(string fieldName, string orderBy, string orderType) {
            BS.Common.BSFrameworkService.GetPageListItemsRequest inValue = new BS.Common.BSFrameworkService.GetPageListItemsRequest();
            inValue.Body = new BS.Common.BSFrameworkService.GetPageListItemsRequestBody();
            inValue.Body.fieldName = fieldName;
            inValue.Body.orderBy = orderBy;
            inValue.Body.orderType = orderType;
            BS.Common.BSFrameworkService.GetPageListItemsResponse retVal = ((BS.Common.BSFrameworkService.PageServiceSoap)(this)).GetPageListItems(inValue);
            return retVal.Body.GetPageListItemsResult;
        }
    }
}
